# Generated by Django 4.1.3 on 2022-11-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('rc', models.IntegerField()),
                ('yc', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('mp', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
    ]
